apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: roo-test
spec:
  image: rabbitmq:3.9.11-management-alpine
  replicas: 3
  resources:
    limits:
      cpu: 1000m
      memory: 1200Mi
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: receiver
  labels:
    app: roo-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: receiver
  template:
    metadata:
      labels:
        app: receiver
    spec:
      containers:
      - name: receive
        image: roothorp/receiver:latest
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
        env:
          - name: RABBITMQ_USERNAME
            valueFrom:
              secretKeyRef:
                name: roo-test-default-user
                key: username
          - name: RABBITMQ_PASSWORD
            valueFrom:
              secretKeyRef:
                name: roo-test-default-user
                key: password
--- 
apiVersion: batch/v1
kind: Job
metadata: 
  name: sender
  labels:
    app: roo-test
spec:
  completions: 10
  parallelism: 2
  template:
    metadata:
      labels:
        app: sender
    spec:
      restartPolicy: Never
      containers:
      - name: send
        image: roothorp/sender:0.2
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
        env:
          - name: RABBITMQ_USERNAME
            valueFrom:
              secretKeyRef:
                name: roo-test-default-user
                key: username
          - name: RABBITMQ_PASSWORD
            valueFrom:
              secretKeyRef:
                name: roo-test-default-user
                key: password
